version: '3.8'

services:
  spleeter:
    image: deezer/spleeter:3.8
    platform: linux/amd64
    volumes:
      - spleeter_data:/output
    command: tail -f /dev/null  # Keep container running

  queue-worker:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.worker
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - spleeter_data:/tmp/stems
    depends_on:
      - spleeter

volumes:
  spleeter_data: 