version: '3.8'

services:
  spleeter:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.spleeter
    volumes:
      - ./test_audio:/app/input
      - ./output_stems:/app/output
    environment:
      - PYTHONUNBUFFERED=1 